### PR TITLE
Memory interface type check

### LINKED ISSUE #372: Interface-Type restriction not applied
Both `L1-Data-Memory` and `L1-Instruction-Memory` `Interface-Type` option has restrictions possibly based on the `Simulation-Mode` in use. Namely, only a `Flat` value can be used for `L1-Instruction-Memory` and only a non-`Flat` `L1-Data-Memory` value can be used if the `Simulation-Mode` is set to be `outoforder`.

Additionally, the outoforder tests in the regression test suite should use a `Fixed` `L1-Data-Memory` for a more realistic testing scenario.

### PR DESCRIPTION
**Pull request by jj16791**
This PR applies the restrictions for memory interface types possibly based on the Simulation-Mode in use. It also updates the regression test suite to use a fixed L1D for outoforder tests.

closes #372

### CODE REVIEW

File: src/lib/config/ModelConfig.cc [hunk 1]
```diff
@@ -886,6 +886,29 @@ void ModelConfig::postValidation() {
...
+  // Currently, only outoforder core types can use non-Flat L1-Data-Memory
+  // interfaces
+  if (configTree_["Core"]["Simulation-Mode"].as<std::string>() !=
+      "outoforder") {
+    std::string l1dType =
+        configTree_["L1-Data-Memory"]["Interface-Type"].as<std::string>();
+    if (l1dType != "Flat")
+      invalid_
+          << "\t- Only a 'Flat' L1-Data-Memory Interface-Type may be used "
+             "for a non-outoforder Simulation-Mode. Interface-Type used is "
```
Comment (FinnWilkinson) [inline src/lib/config/ModelConfig.cc:901]: Rather than "a non-outoforder", have the message print out the simulation mode chosen.

**Review by FinnWilkinson — APPROVED** [review]
All looks good - one minor suggestion but won't block on this

File: src/lib/config/ModelConfig.cc (hunk 1 above)
Comment (jj16791) [reply src/lib/config/ModelConfig.cc:901]: Good idea

**Review by FinnWilkinson — APPROVED** [review]

**Review by dANW34V3R — APPROVED** [review]
Looks good

**Review by JosephMoore25 — APPROVED** [review]
Looks all good, nice work

**Review by ABenC377 — APPROVED** [review]
